### PR TITLE
Fix all deprecation warnings

### LINKED ISSUE #109: Build failure on ROS 2 Rolling Buildfarm
`robotiq_controllers` is failing to build on the Rolling Buildfarm. It looks like #108 fixes the build but the changes have not been bloomed yet. We are proceeding with the next [Rolling Sync](https://discourse.openrobotics.org/t/preparing-for-rolling-sync-2025-12-01) which will remove these packages from the buildfarm. They can be added back in a subsequent sync provided the changes are bloomed successfully.

Details: https://build.ros2.org/view/Rbin_uN64/job/Rbin_uN64__robotiq_controllers__ubuntu_noble_amd64__binary/193/console

```
18:54:41 /tmp/binarydeb/ros-rolling-robotiq-controllers-0.0.1/src/robotiq_activation_controller.cpp:109:59: error: ‘__gnu_cxx::__alloc_traits<std::allocator<hardware_interface::LoanedCommandInterface>, hardware_interface::LoanedCommandInterface>::value_type’ {aka ‘class hardware_interface::LoanedCommandInterface’} has no member named ‘get_value’; did you mean ‘set_value’?
18:54:41   109 |   while (command_interfaces_[REACTIVATE_GRIPPER_RESPONSE].get_value() == ASYNC_WAITING) {
18:54:41       |                                                           ^~~~~~~~~
18:54:41       |                                                           set_value
18:54:41 /tmp/binarydeb/ros-rolling-robotiq-controllers-0.0.1/src/robotiq_activation_controller.cpp:112:68: error: ‘__gnu_cxx::__alloc_traits<std::allocator<hardware_interface::LoanedCommandInterface>, hardware_interface::LoanedCommandInterface>::value_type’ {aka ‘class hardware_interface::LoanedCommandInterface’} has no member named ‘get_value’; did you mean ‘set_value’?
18:54:41   112 |   resp->success = command_interfaces_[REACTIVATE_GRIPPER_RESPONSE].get_value();
18:54:41       |                                                                    ^~~~~~~~~
18:54:41       |                                                                    set_value
18:54:41 make[4]: *** [CMakeFiles/robotiq_controllers.dir/build.make:79: 
```

### PR DESCRIPTION
**Pull request by sea-bass**
Lots of deprecation warnings... ros2_control maintainers have been busy / this repo has been in need of love.

Would appreciate some testing if possible by someone who has a robotiq, but hopefully "it just works" ™️

### CODE REVIEW

**Comment by sea-bass** [comment]
@nbbrooks @christophfroehlich this seems to make CI green per the last PR

**Review by christophfroehlich — APPROVED** [review]
LGTM

File: robotiq_controllers/src/robotiq_activation_controller.cpp [hunk 1]
```diff
@@ -105,14 +105,19 @@ rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn Roboti
...
   {
+    const auto maybe_value = command_interfaces_[REACTIVATE_GRIPPER_RESPONSE].get_optional();
+    if (maybe_value && maybe_value.value() != ASYNC_WAITING)
+    {
+      break;
+    }
     std::this_thread::sleep_for(std::chrono::milliseconds(50));
   }
-  resp->success = command_interfaces_[REACTIVATE_GRIPPER_RESPONSE].get_value();
+  resp->success &= command_interfaces_[REACTIVATE_GRIPPER_RESPONSE].get_optional().has_value();
```
Comment (christophfroehlich) [inline robotiq_controllers/src/robotiq_activation_controller.cpp]: I'm not familiar with this code here, but should this really be has_value()?
```suggestion
  if (resp->success &= command_interfaces_[REACTIVATE_GRIPPER_RESPONSE].get_optional().has_value()) {
    resp->success &= command_interfaces_[REACTIVATE_GRIPPER_RESPONSE].get_optional().value();
  }
```
This would have more similar logic to before.

**Review by christophfroehlich — CHANGES_REQUESTED** [review]
or maybe not, see my comment

File: robotiq_controllers/src/robotiq_activation_controller.cpp (hunk 1 above)
Comment (sea-bass) [reply robotiq_controllers/src/robotiq_activation_controller.cpp]: So `get_value()` returns a double, I think this was being implicitly cast before which is why I changed it.

Comment (sea-bass) [reply robotiq_controllers/src/robotiq_activation_controller.cpp]: In fact, with some of the other changes in this PR using the value instead of a boolean expression causes a compilation error!

Comment (christophfroehlich) [reply robotiq_controllers/src/robotiq_activation_controller.cpp]: I see the problem with the cast, but get_optional.has_value() is not the same as get_value() before. (as I said, I don't know what info is actually in the interface).

Comment (sea-bass) [reply robotiq_controllers/src/robotiq_activation_controller.cpp]: fair point, I kept the old behavior and left a comment for someone who knows what's supposed to happen to maybe fix it later

**Review by christophfroehlich — APPROVED** [review]
I see that I opened already a PR to fix some deprecations, but I close #98 then
